Created lib
arturminchukov/arr-lib pull request #1
Opened 2018-12-07 14:45 UTC by arturminchukov

2018-12-07 15:16 UTC, AntonPashkowskiy commented on arr.js
> +var arr = (function () {
нет смысла экономить буквы на имени библиотеки. arr -> customArrays или что-то вроде того

2018-12-07 15:16 UTC, AntonPashkowskiy commented on arr.js
> +                return array;
не совсем понятно зачем возвращать весь массив. тот же take([1, 2, 3], 0) должен дать пустой массив. take([1, 3, 4]) обычно выдаёт первый элемент [1].

2018-12-07 15:16 UTC, AntonPashkowskiy commented on arr.js
> +            for (var i = n, j = 0; i < array.length; i++) {
`for (var i = n, j = 0; i < array.length; i++, j++) {` - тоже можно

2018-12-07 15:16 UTC, AntonPashkowskiy commented on arr.js
> +                answer[i] = array[i];
используй, пожалуйста функцию push. такое присваивание немного сбивает с толку. для всех остальных функций тоже)

2018-12-07 15:16 UTC, AntonPashkowskiy commented on arr.js
> +                initialValue = callback(initialValue, array[i], i, array);
Лучше присвоить initialValue другой переменной и посчитать всё с ней. То что ты оперируешь с переменной, которая по факту читается как константа - сбивает с толку.

2018-12-07 15:16 UTC, AntonPashkowskiy commented on arr.js
> +                    j++;
то же самое. можно внести в for.

2018-12-07 15:16 UTC, AntonPashkowskiy commented on arr.js
> +                if (callback(array[i], i, array)) {
я бы поостерёгся прокидывать массив в callback. если его кто-то изменить в callback может получится что-то не очень хорошее. обычно передают только элемент и индекс

2018-12-07 15:20 UTC, arturminchukov commented on arr.js
> +            for (var i = n, j = 0; i < array.length; i++) {
здесь я не всегда увеличиваю `j`, поэтому я не внес в `for`

2018-12-07 15:21 UTC, arturminchukov commented on arr.js
> +                    j++;
Здесь также не в каждом проходе цикла нужно увеличивать `j` , поэтому я не в носил в `for`

2018-12-07 15:26 UTC, arturminchukov commented on arr.js
> +                if (callback(array[i], i, array)) {
Здесь я опирался на уже готовые методы array(в частности на filter) и там они прокидывают array в callback

`var newArray = arr.filter(callback(element[, index[, array]])[, thisArg])`
c сайта [сайт](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter)

2018-12-10 07:41 UTC, AntonPashkowskiy requested changes

2018-12-10 07:41 UTC, AntonPashkowskiy commented on arr.js
> +            for (var i = n, j = 0; i < array.length; i++) {
Всмысле не всегда, если в конце каждого цикла j++ без всяких условий. Это же вроде как одно и то же)

2018-12-10 07:41 UTC, AntonPashkowskiy commented on arr.js
> +                if (callback(array[i], i, array)) {
окей

2018-12-10 07:41 UTC, AntonPashkowskiy commented on arr.js
> +                    j++;
тут согласен

2018-12-10 07:41 UTC, AntonPashkowskiy commented on arr.js
> +            return chainArr;
на свежую голову понял идею) круто) вот прямо то что нужно)

2018-12-10 07:41 UTC, AntonPashkowskiy commented on arr.js
> +                    var firstelements = this.take(arguments, arguments.length - 1);
firstelements -> firstElements

2018-12-10 07:41 UTC, AntonPashkowskiy commented on arr.js
> +                    this.cache[cacheSum] = this.sum.apply(this, firstelements) + lastElement;
Как я понял оно закэширует суммы всех элементов до первого. То есть работает как рекурсия уменьшая массив с конца. Если так то это очень плохое решение. У тебя на сумму одного массива мало того что создаётся строчка-хэш, которая тратит больше ресурсов чем сумма самих элементов (ну да ладно, задача такая, скажем так мемоизация тут не очень нужна), но то что оно эту функцию выполнит n раз, при n = длинна массива - убъёт производительность полностью. Просто суммируй элементы и записывай их в кэш по ключу, если значения нет.

2018-12-11 06:37 UTC, AntonPashkowskiy approved these changes

2018-12-11 06:37 UTC, merged